[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
multi_sig_smart_contract = "9zcFR2MWpuJSP7N6PgDeCAGZJ7C2EzzN5hYDLvy7AF4T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "ANCHOR_LOG=true yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
